name: kilimanjaro_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  rxdart:
  http:
  font_awesome_flutter: ^8.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  fonts:
  - family: nicefont
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
        